import product1 from "@/asset/images/products/batch-pump-blp-w-25-327b6bd1.png";
import product2 from "@/asset/images/products/blend-e025-c6952c5a.png";
import product3 from "@/asset/images/products/blend-seventy-96e0b7a1.png";
import product4 from "@/asset/images/products/fslm-600-feacd11b.png";
import product5 from "@/asset/images/products/fslm-1200-f5f95889.png";
import product6 from "@/asset/images/products/fslm-2600r-cde1c5eb.png";
import product7 from "@/asset/images/products/fslm-3500r-7820e159.png";
import product8 from "@/asset/images/products/fslm-3500rh-5a45c43a.png";
import product9 from "@/asset/images/products/fslm-3500rw-ff1f690b.png";
import product10 from "@/asset/images/products/fslm-4000-r-f2871c46.png";
import product11 from "@/asset/images/products/fslm-5500-r-e60dcb1a.jpg";
import product12 from "@/asset/images/products/fslm-6500-r-721c9615.jpg";
import product13 from "@/asset/images/products/hbt50s-13-44c088b7.png";
import product14 from "@/asset/images/products/hbt80-16-176-44c088b7.png";
import product15 from "@/asset/images/products/ihi-ipf110b-8e21-1a5d193d.png";
import product16 from "@/asset/images/products/ihi-ipj70b-4n18-e04c67e8.png";
import product17 from "@/asset/images/products/pb17b-3r-ii-5137aaf9.png";
import product18 from "@/asset/images/products/pb32a-3r-ii-5137aaf9.png";
import product19 from "@/asset/images/products/s-schwing-s28-x-cc5ebe7c.png";
import product20 from "@/asset/images/products/schwing-s20-cc5ebe7c.png";
import product21 from "@/asset/images/products/schwing-s31-xt-cc5ebe7c.png";
import product22 from "@/asset/images/products/schwing-s32-x-cc5ebe7c.png";
import product23 from "@/asset/images/products/trailer-batch-pump-blp-w-25-a4aa4880.png";
import product24 from "@/asset/images/products/truemax-lp50-10-60du-34a1ef5c.png";
import product25 from "@/asset/images/products/zoomlion-10020r-0f621270.png";
import product26 from "@/asset/images/products/zoomlion-qy-25-a4f13453.png";
import product27 from "@/asset/images/products/zoomlion-qy-55-d27c5c87.png";
import product28 from "@/asset/images/products/IHI-IPG-115B-8E26_4-14A.png";
import product29 from "@/asset/images/products/IHI-IPG-125B-6N33_4.png";
import product30 from "@/asset/images/products/IHI-IPG-135B-6N36_4.png";

const ProductData = [
  product1,
  product2,
  product3,
  product4,
  product5,
  product6,
  product7,
  product8,
  product9,
  product10,
  product11,
  product12,
  product13,
  product14,
  product15,
  product16,
  product17,
  product18,
  product19,
  product20,
  product21,
  product22,
  product23,
  product24,
  product25,
  product26,
  product27,
  product28,
  product29,
  product30,
];

export default ProductData;

export const products = [
  {
    id: "d469c5d120c5",
    name: "Schwing S20",
    slug: "schwing-s20",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[19]",
    localImage: "schwing-s20-cc5ebe7c.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "19.4 m",
        "Maximum horizontal reach": "15.8 m",
        "Maximum depth reach": "10.8 m",
        "Minimum unfolding height": "3.9 m",
        "Section numbers": 4,
        "Boom type": "Z",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "111 cu m/h",
        "Maximum theoretical pressure on concrete": "70 bar",
        "Concrete cylinders (diam. × stroke)": "200 mm x 2000m",
        "Hydraulic circuit": "Open",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "1b9509e2d35a",
    name: "S Schwing S28 X",
    slug: "s-schwing-s28-x",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[18]",
    localImage: "s-schwing-s28-x-cc5ebe7c.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "27.7 m",
        "Maximum horizontal reach": "23.7 m",
        "Maximum depth reach": "18 m",
        "Minimum unfolding height": "5.8 m",
        "Section numbers": 4,
        "Boom type": "Z",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "161/100 cu m/h",
        "Maximum theoretical pressure on concrete": "65/69 bar",
        "Concrete cylinders (diam. × stroke)": "230 mm x 2006.6 mm",
        "Hydraulic circuit": "MPS",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "764a656c03ab",
    name: "Schwing S31 XT",
    slug: "schwing-s31-xt",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[20]",
    localImage: "schwing-s31-xt-cc5ebe7c.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "30.5 m",
        "Maximum horizontal reach": "26.5 m",
        "Maximum depth reach": "14.3 m",
        "Minimum unfolding height": "5.7 m",
        "Section numbers": 5,
        "Boom type": "Z",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "159 cu m/h",
        "Maximum theoretical pressure on concrete": "69 bar",
        "Concrete cylinders (diam. × stroke)": "230 mm x 2000m",
        "Hydraulic circuit": "MPS",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "9f319693c438",
    name: "Schwing S32 X",
    slug: "schwing-s32-x",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[21]",
    localImage: "schwing-s32-x-cc5ebe7c.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "31.9 m",
        "Maximum horizontal reach": "28 m",
        "Maximum depth reach": "20.5 m",
        "Minimum unfolding height": "7.55 m",
        "Section numbers": 4,
        "Boom type": "Z",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "159 cu m/h",
        "Maximum theoretical pressure on concrete": "69 bar",
        "Concrete cylinders (diam. × stroke)": "230 mm x 2006.6 mm",
        "Hydraulic circuit": "MPS",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "4c3056fba477",
    name: "Schwing S36 X",
    slug: "schwing-s36-x",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[19]",
    localImage: "schwing-s20-cc5ebe7c.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "35.2 m",
        "Maximum horizontal reach": "31.2 m",
        "Maximum depth reach": "24 m",
        "Minimum unfolding height": "8.3 m",
        "Section numbers": 4,
        "Boom type": "Full Articulation, Roll & Fold®",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "136 cu m/h",
        "Maximum theoretical pressure on concrete": "76 bar",
        "Concrete cylinders (diam. × stroke)": "254 mm x 2000 mm",
        "Hydraulic circuit": "MPS",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "dbe8397861c1",
    name: "Schwing S38 SX",
    slug: "schwing-s38-sx",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[19]",
    localImage: "schwing-s20-cc5ebe7c.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "37.3 m",
        "Maximum horizontal reach": "32.6 m",
        "Maximum depth reach": "25.9 m",
        "Minimum unfolding height": "8.3 m",
        "Section numbers": 5,
        "Boom type": "Hyper Extension",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "163 cu m/h",
        "Maximum theoretical pressure on concrete": "81 bar",
        "Concrete cylinders (diam. × stroke)": "254 mm x 2500 mm",
        "Hydraulic circuit": "MPS",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "e09e6d7697bc",
    name: "IHI IPF110B-8E21",
    slug: "ihi-ipf110b-8e21",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[14]",
    localImage: "ihi-ipf110b-8e21-1a5d193d.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "20.9m",
        "Maximum horizontal reach": "17.0m",
        "Maximum depth reach": "18 m",
        "Minimum unfolding height": "3.9 m",
        "Section numbers": 4,
        "Boom type": "M Type",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "10-100m3/h ",
        "Maximum theoretical pressure on concrete": "8.09MPa (82.6kgf/cm2)",
        "Concrete cylinders (diam. × stroke)": "220 mm x 1600 mm",
        "Hydraulic circuit": "open",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "89e0179113c7",
    name: "IHI IPF50B-4N14",
    slug: "ihi-ipf50b-4n14",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[19]",
    localImage: "schwing-s20-cc5ebe7c.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "14m",
        "Maximum horizontal reach": "10.7m",
        "Maximum depth reach": "-",
        "Minimum unfolding height": "2.75",
        "Section numbers": 3,
        "Boom type": "M Type",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "10-50m3/h",
        "Maximum theoretical pressure on concrete":
          "Maximum 4.65Mpa (47.5kgf/cm2)",
        "Concrete cylinders (diam. × stroke)": "180 mm x 900 mm",
        "Hydraulic circuit": "open",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "e1687e414eb3",
    name: "IHI IPF60B-5N17/4",
    slug: "ihi-ipf60b-5n17-4",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[19]",
    localImage: "schwing-s20-cc5ebe7c.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "16.8m",
        "Maximum horizontal reach": "13.3m",
        "Maximum depth reach": "8m",
        "Minimum unfolding height": "2.75",
        "Section numbers": 4,
        "Boom type": "M Type",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "10-60m3/h",
        "Maximum theoretical pressure on concrete":
          "Maximum 4.9MPa (50kgf/cm2)",
        "Concrete cylinders (diam. × stroke)": "180 mm x 1150 mm",
        "Hydraulic circuit": "open",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "73de41a01316",
    name: "IHI IPJ70B-4N18",
    slug: "ihi-ipj70b-4n18",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[15]",
    localImage: "ihi-ipj70b-4n18-e04c67e8.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "16.6m",
        "Maximum horizontal reach": "14.6m",
        "Maximum depth reach": "7,25m",
        "Minimum unfolding height": "2.75",
        "Section numbers": 4,
        "Boom type": "3-stage Z-shape",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "10-70m3/h",
        "Maximum theoretical pressure on concrete": "Max 4.17MPa (42.6kgf/cm2)",
        "Concrete cylinders (diam. × stroke)": "205mm x 1200mm",
        "Hydraulic circuit": "open",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "kyokuto-py115a-26c",
    name: "PY115A-26C",
    slug: "kyokuto-py115a-26c",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[19]",
    localImage: "kyokuto-py115a-26c.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "25.8m",
        "Maximum horizontal reach": "21.8m",
        "Maximum depth reach": "12.4m",
        "Minimum unfolding height": "3.5 m",
        "Section numbers": 4,
        "Boom type": "M Type",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "115m3/h",
        "Maximum theoretical pressure on concrete": "7.8Mpa",
        "Concrete cylinders (diam. × stroke)": "220 mm x 1600 mm",
        "Hydraulic circuit": "open",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "kyokuto-py115a-26b",
    name: "PY115A-26B",
    slug: "kyokuto-py115a-26b",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[19]",
    localImage: "kyokuto-py115a-26b.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "25.8m",
        "Maximum horizontal reach": "21.8m",
        "Maximum depth reach": "12.4m",
        "Minimum unfolding height": "3.5 m",
        "Section numbers": 4,
        "Boom type": "M Type",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "115m3/h",
        "Maximum theoretical pressure on concrete": "7.8Mpa",
        "Concrete cylinders (diam. × stroke)": "225 mm x 1650 mm",
        "Hydraulic circuit": "open",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "ihi-pg115b-8e26-4",
    name: "PG115B-8E26/4",
    slug: "ihi-pg115b-8e26-4",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[27]",
    localImage: "ihi-pg115b-8e26-4.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "25.5m",
        "Maximum horizontal reach": "21.5m",
        "Maximum depth reach": "14.89m",
        "Minimum unfolding height": "3.45 m",
        "Section numbers": 3,
        "Boom type": "3-stage Z-shape",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "10-115m3/h",
        "Maximum theoretical pressure on concrete": "7.04MPa (71.8kgf/cm2)",
        "Concrete cylinders (diam. × stroke)": "220mm x 1600mm",
        "Hydraulic circuit": "open",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "ihi-ipg135b-6n33-4",
    name: "IPG 135B-6N33/4",
    slug: "ihi-ipg135b-6n33-4",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[28]",
    localImage: "ihi-ipg135b-6n33-4.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "32.6m",
        "Maximum horizontal reach": "29.2m",
        "Maximum depth reach": "20.3m",
        "Minimum unfolding height": "3.4m",
        "Section numbers": 4,
        "Boom type": "M Type",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "135m3/h",
        "Maximum theoretical pressure on concrete": "3.9MPaX320Lit/min",
        "Concrete cylinders (diam. × stroke)": "220mm x 1800m",
        "Hydraulic circuit": "open",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "ihi-pg135b-6n36-4",
    name: "PG135B-6N36/4",
    slug: "ihi-pg135b-6n36-4",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[29]",
    localImage: "ihi-pg135b-6n36-4.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "35m",
        "Maximum horizontal reach": "32.15m",
        "Maximum depth reach": "23m",
        "Minimum unfolding height": "3.4 m",
        "Section numbers": 4,
        "Boom type": "M Type",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "135m3/h",
        "Maximum theoretical pressure on concrete": "3.9MPax320Lit/min",
        "Concrete cylinders (diam. × stroke)": "220mm x 2200mm",
        "Hydraulic circuit": "open",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "ihi-ipg115b-8e26-4",
    name: "IPG115B-8E26/4",
    slug: "ihi-ipg115b-8e26-4",
    brand: "Concrete Pump",
    category: "concrete-pump",
    className: "product-item",
    imageUrl: "ProductData[ProductData[18]",
    localImage: "ihi-ipg115b-8e26-4.png",
    details: {
      BOOM: {
        "Maximum vertical reach": "30m",
        "Maximum horizontal reach": "25.95m",
        "Maximum depth reach": "14.89m",
        "Minimum unfolding height": "18",
        "Section numbers": 3,
        "Boom type": "3-stage Z-shape",
        "Pipeline diameter": "125mm",
      },
      PUMP: {
        "Maximum theoretical output": "10-115m3/h",
        "Maximum theoretical pressure on concrete": "40Kgf/cm2 x320 Lit/min",
        "Concrete cylinders (diam. × stroke)": "220mm x 1600mm",
        "Hydraulic circuit": "open",
      },
      CHASSIS: {
        "Chassis brand": "Multiple Choices",
      },
    },
    url: null,
  },
  {
    id: "4ca6cc365a50",
    name: "ZOOMLION 10020R",
    slug: "zoomlion-10020r",
    brand: "Moli",
    category: "moli",
    className: "product-item-moli",
    imageUrl: "ProductData[24]",
    localImage: "zoomlion-10020r-0f621270.png",
    details: {
      "Maximum theorical output": "100/55m3/h",
      "Maximum theorical pressure on concrete": "20/11Mpa",
      "Distribution valve type": "S Valve",
      "Concrete cylinder": "Φ200mm×1650mm",
      "Hopper capacity×feeding height": "600L×1500mm",
      "Recommended concrete slump": "12-23cm",
      "Rated power": "199/2300kW/(r/min)",
      "Engine moment": "1200/1200-1500N.m/(r/min)",
      "Maximum displacement": "7470cc",
      "Total weight": "13800kg",
      "Length×width×height": "9100mm×2450mm×3140mm",
    },
    url: null,
  },
  {
    id: "47f067db989b",
    name: "TRUEMAX LP50.10.60DU",
    slug: "truemax-lp50-10-60du",
    brand: "Moli",
    category: "moli",
    className: "product-item-moli",
    imageUrl: "ProductData[23]",
    localImage: "truemax-lp50-10-60du-34a1ef5c.png",
    details: {
      "Maximum theorical output": "49/26 m3/h",
      "Maximum theorical pressure on concrete": "5/10 Mpa",
      "Distribution valve type": "S Valve",
      "Concrete cylinder": "Ф180×1200 mm",
      "Hopper capacity×feeding height": "0.5×1370",
      "Recommended concrete slump": "12-23cm",
      "Rated power": "60 kW",
      "Engine moment": "2000 r/min",
      "Maximum displacement": "7470cc",
      "Total weight": "500 Kg",
      "Length×width×height": "5200X2100X02500",
    },
    url: null,
  },
  {
    id: "4c582725423f",
    name: "HBT50S-13",
    slug: "hbt50s-13",
    brand: "Citi Pump",
    category: "stationery-concrete",
    className: "product-item-stationary",
    imageUrl: "ProductData[12]",
    localImage: "hbt50s-13-44c088b7.png",
    details: {
      "Maximum theorical output": "49/26m3/h",
      "Maximum theorical pressure on concrete": "50/100bar",
      "Strokes/minute": "98/54m3/h",
      "Concrete cylinder": "Φ180mm×1200mm",
      "Hopper capacity": "600L",
      "Filling height": "1400mm",
      "Maximum aggregate diameter": "50/Φ150mm",
      "Inside diameter of delivering pipe": "40/Φ125mm",
      "Inside diameter of pipe": "Φ125/Φ150mm",
      "Hydraulic system type": "Open",
      Power: "60kW",
      "Length×width×height": "4894mm×1539mm×2043mm",
      Weight: "191kW",
    },
    url: null,
  },
  {
    id: "86347386bc49",
    name: "HBT80-16-176",
    slug: "hbt80-16-176",
    brand: "Citi Pump",
    category: "stationery-concrete",
    className: "product-item-stationary",
    imageUrl: "ProductData[13]",
    localImage: "hbt80-16-176-44c088b7.png",
    details: {
      "Maximum theorical output": "81/49m3/h",
      "Maximum theorical pressure on concrete": "90/160bar",
      "Strokes/minute": "100/200bar",
      "Concrete cylinder": "Φ200mm×1650mm",
      "Hopper capacity": "600L",
      "Filling height": "1450mm",
      "Maximum aggregate diameter": "50/Φ150mm",
      "Inside diameter of delivering pipe": "40/Φ125mm",
      "Inside diameter of pipe": "Φ125/Φ150mm",
      "Hydraulic system type": "Open",
      Power: "174kW",
      "Length×width×height": "6600mmx1930mmx2190mm",
      Weight: "6800mmx1930mmx2190mm",
    },
    url: null,
  },
  {
    id: "8df15461debc",
    name: "HBT100-20-191",
    slug: "hbt100-20-191",
    brand: "Citi Pump",
    category: "stationery-concrete",
    className: "product-item-stationary",
    imageUrl: "ProductData[12]",
    localImage: "hbt50s-13-44c088b7.png",
    details: {
      "Maximum theorical output": "98/54m3/h",
      "Maximum theorical pressure on concrete": "23/14Min -1",
      "Strokes/minute": "27.3/15.8Min -1",
      "Concrete cylinder": "Φ180mm×1800mm",
      "Hopper capacity": "600L",
      "Filling height": "1450mm",
      "Maximum aggregate diameter": "50/Φ150mm",
      "Inside diameter of delivering pipe": "40/Φ125mm",
      "Inside diameter of pipe": "Φ125/Φ150mm",
      "Hydraulic system type": "Open",
      Power: "191kW",
      "Length×width×height": "6600kg",
      Weight: "7600kg",
    },
    url: null,
  },
  {
    id: "bfac05b5e8a1",
    name: "SP 2800",
    slug: "sp-2800",
    brand: "Stationery Concrete",
    category: "stationery-concrete",
    className: "product-item-stationary",
    imageUrl: "ProductData[12]",
    localImage: "hbt50s-13-44c088b7.png",
    details: {
      "Maximum theorical output": "58/101m3/h",
      "Maximum theorical pressure on concrete": "119/66 bar",
      "Strokes/minute": 2200,
      "Concrete cylinder": "200mmx1600mm",
      "Hopper capacity": "600L",
      "Filling height": "-",
      "Maximum aggregate diameter": "50/Φ150mm",
      "Inside diameter of delivering pipe": "40/Φ125mm",
      "Inside diameter of pipe": "Φ125/Φ150mm",
      "Hydraulic system type": "Open",
      Power: "132kW",
      "Length×width×height": "-",
      Weight: "5300kg",
    },
    url: null,
  },
  {
    id: "f2ae5246391d",
    name: "SP 3000",
    slug: "sp-3000",
    brand: "Stationery Concrete",
    category: "stationery-concrete",
    className: "product-item-stationary",
    imageUrl: "ProductData[12]",
    localImage: "hbt50s-13-44c088b7.png",
    details: {
      "Maximum theorical output": "35/64m3h",
      "Maximum theorical pressure on concrete": "156/86 bar",
      "Strokes/minute": 2100,
      "Concrete cylinder": "180mmx1600mm",
      "Hopper capacity": "400L",
      "Filling height": "-",
      "Maximum aggregate diameter": "50/Φ150mm",
      "Inside diameter of delivering pipe": "40/Φ125mm",
      "Inside diameter of pipe": "Φ125/Φ150mm",
      "Hydraulic system type": "Open",
      Power: "173kW",
      "Length×width×height": "-",
      Weight: "5500kg",
    },
    url: null,
  },
  {
    id: "1c11c90fba78",
    name: "SP 3500 D/E",
    slug: "sp-3500-d-e",
    brand: "Stationery Concrete",
    category: "stationery-concrete",
    className: "product-item-stationary",
    imageUrl: "ProductData[12]",
    localImage: "hbt50s-13-44c088b7.png",
    details: {
      "Maximum theorical output": "49/79m3/h",
      "Maximum theorical pressure on concrete": "169/100Bar",
      "Strokes/minute": "2100/1450mIN-1",
      "Concrete cylinder": "180mmX2000mm",
      "Hopper capacity": "600L",
      "Filling height": "-",
      "Maximum aggregate diameter": "50/Φ150mm",
      "Inside diameter of delivering pipe": "40/Φ125mm",
      "Inside diameter of pipe": "Φ125/Φ150mm",
      "Hydraulic system type": "Open",
      Power: "181/160kW",
      "Length×width×height": "-",
      Weight: "7000kg",
    },
    url: null,
  },
  {
    id: "011c771febb8",
    name: "SP 4800",
    slug: "sp-4800",
    brand: "Stationery Concrete",
    category: "stationery-concrete",
    className: "product-item-stationary",
    imageUrl: "ProductData[12]",
    localImage: "hbt50s-13-44c088b7.png",
    details: {
      "Maximum theorical output": "43/66m3/h",
      "Maximum theorical pressure on concrete": "243/156 bar",
      "Strokes/minute": "1500Min-1",
      "Concrete cylinder": "180mmX2000mm",
      "Hopper capacity": "600L",
      "Filling height": "-",
      "Maximum aggregate diameter": "50/Φ150mm",
      "Inside diameter of delivering pipe": "40/Φ125mm",
      "Inside diameter of pipe": "Φ125/Φ150mm",
      "Hydraulic system type": "Open",
      Power: "E200",
      "Length×width×height": "-",
      Weight: "8000kg",
    },
    url: null,
  },
  {
    id: "e2a22705ee57",
    name: "HBT50.10.60RS",
    slug: "hbt50-10-60rs",
    brand: "Stationery Concrete",
    category: "stationery-concrete",
    className: "product-item-stationary",
    imageUrl: "ProductData[12]",
    localImage: "hbt50s-13-44c088b7.png",
    details: {
      "Maximum theorical output": "49/26m3/h",
      "Maximum theorical pressure on concrete": "50/100bar",
      "Strokes/minute": "26/13.8Min -1",
      "Concrete cylinder": "Φ180mm×1250mm",
      "Hopper capacity": "500L",
      "Filling height": "1335mm",
      "Maximum aggregate diameter": "50/Φ150mm",
      "Inside diameter of delivering pipe": "40/Φ125mm",
      "Inside diameter of pipe": "Φ125/Φ150mm",
      "Hydraulic system type": "Open",
      Power: "60kW",
      "Length×width×height": "5300mm×2020mm×2550mm",
      Weight: "4500kg",
    },
    url: null,
  },
  {
    id: "a403cbab5dc3",
    name: "HBT60.13.90SU",
    slug: "hbt60-13-90su",
    brand: "Stationery Concrete",
    category: "stationery-concrete",
    className: "product-item-stationary",
    imageUrl: "ProductData[12]",
    localImage: "hbt50s-13-44c088b7.png",
    details: {
      "Maximum theorical output": "67/41m3/h",
      "Maximum theorical pressure on concrete": "70/130bar",
      "Strokes/minute": "19.8/12Min -1",
      "Concrete cylinder": "Φ200mm×1800mm",
      "Hopper capacity": "600L",
      "Filling height": "1450mm",
      "Maximum aggregate diameter": "50/Φ150mm",
      "Inside diameter of delivering pipe": "40/Φ125mm",
      "Inside diameter of pipe": "Φ125/Φ150mm",
      "Hydraulic system type": "Open",
      Power: "90kW",
      "Length×width×height": "7000mm×2200mm×2300mm",
      Weight: "6950kg",
    },
    url: null,
  },
  {
    id: "c3206d4e4277",
    name: "HBT60.13.118RSD",
    slug: "hbt60-13-118rsd",
    brand: "Stationery Concrete",
    category: "stationery-concrete",
    className: "product-item-stationary",
    imageUrl: "ProductData[12]",
    localImage: "hbt50s-13-44c088b7.png",
    details: {
      "Maximum theorical output": "67/41m3/h",
      "Maximum theorical pressure on concrete": "70/130bar",
      "Strokes/minute": "21/13Min -1",
      "Concrete cylinder": "Φ200mm×1710mm",
      "Hopper capacity": "600L",
      "Filling height": "1400mm",
      "Maximum aggregate diameter": "50/Φ150mm",
      "Inside diameter of delivering pipe": "40/Φ125mm",
      "Inside diameter of pipe": "Φ125/Φ150mm",
      "Hydraulic system type": "Open",
      Power: "118kW",
      "Length×width×height": "6700mmx2100mmx2700mm",
      Weight: "6500kg",
    },
    url: null,
  },
  {
    id: "9d5f117fc9a5",
    name: "FSLM 600",
    slug: "fslm-600",
    brand: "Self loading Mixer",
    category: "self-loading-mixer",
    className: "product-item-self",
    imageUrl: "ProductData[3]",
    localImage: "fslm-600-feacd11b.png",
    details: {
      "Concrete theorical output": "600 L /batch",
      "Total Drum Capacity": "1000L",
      "Front Shovel Capacity": "500L",
      "Water tank capacity": "2x200L",
      "Max. Drum Slewing Angle": "0° ",
      Productivity: "5 batch / Hour , 3m3/ h ",
      "Engine Power": "55 kW",
      "Engine Type": "YUNNEI, 490, Turbo-charged",
      "Drive Type": "4x4",
      Transmision: "Automatic, 4 F+4R Shift",
      Weight: "4200 Kg",
      "Overall Size": "6750 x 1810 x 2800 mm",
    },
    url: null,
  },
  {
    id: "4ee143ddf3db",
    name: "FSLM 1200",
    slug: "fslm-1200",
    brand: "Self loading Mixer",
    category: "self-loading-mixer",
    className: "product-item-self",
    imageUrl: "ProductData[4]",
    localImage: "fslm-1200-f5f95889.png",
    details: {
      "Concrete theorical output": "1200 L/ batch",
      "Total Drum Capacity": "1800 L",
      "Front Shovel Capacity": "500L",
      "Water tank capacity": "2x200L",
      "Max. Drum Slewing Angle": "0° ",
      Productivity: "5 batch / Hour , 6m3/ h ",
      "Engine Power": "55 kW",
      "Engine Type": "YUNNEI, 490, Turbo-charged",
      "Drive Type": "4x4",
      Transmision: "Automatic, 4 F+4R Shift",
      Weight: "4500 Kg",
      "Overall Size": "6400 x 2550 x 2450 mm",
    },
    url: null,
  },
  {
    id: "c67b4eb17b58",
    name: "FSLM 1800",
    slug: "fslm-1800",
    brand: "Self loading Mixer",
    category: "self-loading-mixer",
    className: "product-item-self",
    imageUrl: "ProductData[5]",
    localImage: "fslm-1800-f5f95889.png",
    details: {
      "Concrete theorical output": "1800 L / batch",
      "Total Drum Capacity": "2700 L",
      "Front Shovel Capacity": "500L",
      "Water tank capacity": "2x200L",
      "Max. Drum Slewing Angle": "270° ",
      Productivity: "5 batch / Hour , 9m3/ h ",
      "Engine Power": "78 kW",
      "Engine Type": "YUCHAI, 4102, Turbo-charged",
      "Drive Type": "4x4",
      Transmision: "Automatic, 4 F+4R Shift",
      Weight: "5600 Kg",
      "Overall Size": "7300 x 2650 x 2750 mm",
    },
    url: null,
  },
  {
    id: "b76c85e2f08d",
    name: "FSLM 2600R",
    slug: "fslm-2600r",
    brand: "Self loading Mixer",
    category: "self-loading-mixer",
    className: "product-item-self",
    imageUrl: "ProductData[5]",
    localImage: "fslm-2600r-cde1c5eb.png",
    details: {
      "Concrete theorical output": "2600 L / batch",
      "Total Drum Capacity": "3900 L",
      "Front Shovel Capacity": "600 L",
      "Water tank capacity": "2x250L",
      "Max. Drum Slewing Angle": "270° ",
      Productivity: "4 batch / Hour , 10.4m3/ h ",
      "Engine Power": "78 kW",
      "Engine Type": "YUCHAI, 4102, Turbo-charged",
      "Drive Type": "4x4",
      Transmision: "Automatic, 4 F+4R Shift",
      Weight: "6500 Kg",
      "Overall Size": "7860 x 2750 x 3000 mm",
    },
    url: null,
  },
  {
    id: "8fcbcff6128a",
    name: "FSLM 3500R",
    slug: "fslm-3500r",
    brand: "Self loading Mixer",
    category: "self-loading-mixer",
    className: "product-item-self",
    imageUrl: "ProductData[6]",
    localImage: "fslm-3500r-7820e159.png",
    details: {
      "Concrete theorical output": "3500 L / batch",
      "Total Drum Capacity": "5200 L",
      "Front Shovel Capacity": "600 L",
      "Water tank capacity": "2x260L",
      "Max. Drum Slewing Angle": "270° ",
      Productivity: "4 batch / Hour , 14m3/ h ",
      "Engine Power": "85 kW",
      "Engine Type": "YUCHAI, 4105, Turbo-charged",
      "Drive Type": "4x4",
      Transmision: "Automatic, 4 F+4R Shift",
      Weight: "7500 Kg",
      "Overall Size": "7830 x 2680 x 3300 mm",
    },
    url: null,
  },
  {
    id: "f8d3effae8a1",
    name: "FSLM 3500RH",
    slug: "fslm-3500rh",
    brand: "Self loading Mixer",
    category: "self-loading-mixer",
    className: "product-item-self",
    imageUrl: "ProductData[7]",
    localImage: "fslm-3500rh-5a45c43a.png",
    details: {
      "Concrete theorical output": "3500 L / batch",
      "Total Drum Capacity": "5200 L",
      "Front Shovel Capacity": "600 L",
      "Water tank capacity": "2x310L",
      "Max. Drum Slewing Angle": "90° ",
      Productivity: "4 batch / Hour , 14m3/ h ",
      "Engine Power": "85 kW",
      "Engine Type": "YUCHAI, 4105, Turbo-charged",
      "Drive Type": "4x4",
      Transmision: "Automatic, 4 F+4R Shift",
      Weight: "8100 Kg",
      "Overall Size": "7520 x 2600 x 3270 mm",
    },
    url: null,
  },
  {
    id: "1f0a586ab62d",
    name: "FSLM 3500RW",
    slug: "fslm-3500rw",
    brand: "Self loading Mixer",
    category: "self-loading-mixer",
    className: "product-item-self",
    imageUrl: "ProductData[8]",
    localImage: "fslm-3500rw-ff1f690b.png",
    details: {
      "Concrete theorical output": "3500 L / batch",
      "Total Drum Capacity": "5200 L",
      "Front Shovel Capacity": "600 L",
      "Water tank capacity": "2x310L",
      "Max. Drum Slewing Angle": "270° ",
      Productivity: "4 batch / Hour , 14m3/ h ",
      "Engine Power": "85 kW",
      "Engine Type": "YUCHAI, 4105, Turbo-charged",
      "Drive Type": "4x4",
      Transmision: "Automatic, 4 F+4R Shift",
      Weight: "8200 Kg",
      "Overall Size": "7710 x 2900 x 3300 mm",
    },
    url: null,
  },
  {
    id: "77aae34537e3",
    name: "FSLM 4000 R",
    slug: "fslm-4000-r",
    brand: "Self loading Mixer",
    category: "self-loading-mixer",
    className: "product-item-self",
    imageUrl: "ProductData[9]",
    localImage: "fslm-4000-r-f2871c46.png",
    details: {
      "Concrete theorical output": "4000 L / batch",
      "Total Drum Capacity": "6100 L",
      "Front Shovel Capacity": "600 L",
      "Water tank capacity": "2x330L",
      "Max. Drum Slewing Angle": "290° ",
      Productivity: "4 batch / Hour , 16m3/ h ",
      "Engine Power": "85 kW",
      "Engine Type": "YUCHAI, 4105, Turbo-charged",
      "Drive Type": "4x4x4",
      Transmision: "Automatic, 4 F+4R Shift",
      Weight: "9200 Kg",
      "Overall Size": "7500 x 2850 x 3600 mm",
    },
    url: null,
  },
  {
    id: "8b84e58a4c4e",
    name: "FSLM 5500 R",
    slug: "fslm-5500-r",
    brand: "Self loading Mixer",
    category: "self-loading-mixer",
    className: "product-item-self",
    imageUrl: "ProductData[10]",
    localImage: "fslm-5500-r-e60dcb1a.jpg",
    details: {
      "Concrete theorical output": "5500 L / batch",
      "Total Drum Capacity": "8200 L ",
      "Front Shovel Capacity": "800 L ",
      "Water tank capacity": "2 x 430 L",
      "Max. Drum Slewing Angle": "270° ",
      Productivity: "4 batch / Hour , 22m3/ h ",
      "Engine Power": "92 kW",
      "Engine Type": "FAW, 6105, Turbo-charged",
      "Drive Type": "4x4",
      Transmision: "Automatic, 4 F+4R Shift",
      Weight: "11,200 Kg",
      "Overall Size": "8450 x 3100 x 3640 mm",
    },
    url: null,
  },
  {
    id: "27b348216240",
    name: "FSLM 6500 R",
    slug: "fslm-6500-r",
    brand: "Self loading Mixer",
    category: "self-loading-mixer",
    className: "product-item-self",
    imageUrl: "ProductData[11]",
    localImage: "fslm-6500-r-721c9615.jpg",
    details: {
      "Concrete theorical output": "6500 L / batch",
      "Total Drum Capacity": "9700 L",
      "Front Shovel Capacity": "800 L ",
      "Water tank capacity": "2 x 730 L",
      "Max. Drum Slewing Angle": "290° ",
      Productivity: "4 batch / Hour , 26m3/ h ",
      "Engine Power": "92 kW",
      "Engine Type": "DEUTZ, 6105, Turbo-charged",
      "Drive Type": "4x4x4",
      Transmision: "Automatic, 4 F+4R Shift",
      Weight: "12,500 Kg",
      "Overall Size": "8450 x 3050 x 3860 mm",
    },
    url: null,
  },
  {
    id: "b67757af9c85",
    name: "PB17B-3R-II",
    slug: "pb17b-3r-ii",
    brand: "Placing Boom",
    category: "placing-boom",
    className: "product-item-placing",
    imageUrl: "ProductData[16]",
    localImage: "pb17b-3r-ii-5137aaf9.png",
    details: {
      "Maximum Vertical Reach": "17 m",
      Arms: 3,
      "Slewing Range": "360° ",
      "Hydraulic Pressure": "25 Mpa",
      "Model of Slewing": "Turbo Worm Drive",
      "Delivery Pipeline Diameter": "φ133×4.5 mm",
      "Total Weight": "6500 kg",
      "Max Lifting Unit": "1520 kg",
    },
    url: null,
  },
  {
    id: "dd6f67624cee",
    name: "PB32A-3R-II",
    slug: "pb32a-3r-ii",
    brand: "Placing Boom",
    category: "placing-boom",
    className: "product-item-placing",
    imageUrl: "ProductData[17]",
    localImage: "pb32a-3r-ii-5137aaf9.png",
    details: {
      "Maximum Vertical Reach": "31.7 m",
      Arms: 4,
      "Slewing Range": "360° ",
      "Hydraulic Pressure": "28 Mpa",
      "Model of Slewing": "Gear Slewing",
      "Delivery Pipeline Diameter": "φ133×4.5 mm",
      "Total Weight": "18150 kg",
      "Max Lifting Unit": "4150 kg",
    },
    url: null,
  },
  {
    id: "18833a05252a",
    name: "PB28A-3R-II",
    slug: "pb28a-3r-ii",
    brand: "Placing Boom",
    category: "placing-boom",
    className: "product-item-placing",
    imageUrl: "ProductData[16]",
    localImage: "pb17b-3r-ii-5137aaf9.png",
    details: {
      "Maximum Vertical Reach": "27.7 m",
      Arms: 4,
      "Slewing Range": "360° ",
      "Hydraulic Pressure": "28 Mpa",
      "Model of Slewing": "Gear Slewing",
      "Delivery Pipeline Diameter": "φ133×4.5 mm",
      "Total Weight": "16200 kg",
      "Max Lifting Unit": "4100 kg",
    },
    url: null,
  },
  {
    id: "f3a877bf9401",
    name: "Blend E025",
    slug: "blend-e025",
    brand: "Blend Plant",
    category: "blend-plant",
    className: "product-item-bland",
    imageUrl: "ProductData[1]",
    localImage: "blend-e025-c6952c5a.png",
    details: {
      Aggregates: "5 m3",
      Cement: "2.3 m3",
      Water: "1500 / 3000 lt ( Opt )",
      Emulsion: "300 ltr ",
      Admixtures: "3x42 lt (ops)",
      Output: "<50 m3/h",
      Power: "44 kW PTO",
      "Empty Weight": "2870kg",
      DimensionS: "4317 x 2250 x 1994 mm",
    },
    url: null,
  },
  {
    id: "f6a430a22afb",
    name: "Blend Seventy",
    slug: "blend-seventy",
    brand: "Blend Plant",
    category: "blend-plant",
    className: "product-item-bland",
    imageUrl: "ProductData[2]",
    localImage: "blend-seventy-96e0b7a1.png",
    details: {
      Aggregates: "12 m3",
      Cement: "2.3 m3",
      Water: "2.000/4000 ( Opt )",
      Emulsion: "600 lt (Opt)",
      Admixtures: "3x42 lt (ops)",
      Output: "<50 m3/h",
      Power: "45 kW PTO",
      "Empty Weight": "3750 kg",
      DimensionS: "6150 x 2250 x 2276 mm",
    },
    url: null,
  },
  {
    id: "3910ef5533d3",
    name: "Batch Pump BLP - W/25",
    slug: "batch-pump-blp-w-25",
    brand: "Batch pump",
    category: "batch-pump",
    className: "product-item-batch",
    imageUrl: "ProductData[0]",
    localImage: "batch-pump-blp-w-25-327b6bd1.png",
    details: {
      "Max. Theo Pumping Output": "40 m3/h",
      "System Pressure": "28 Mpa",
      "Delivery Cylinder x Stroke ": "Φ200X1000",
      "Distribute Valve": "S Valve",
      Generator: "100 kW",
      "Main Motor": "37 kW",
      "Main Pump": "Flutek Kawasaki K3V112",
      "Hopper Capacity": "1.8 m3",
    },
    url: null,
  },
  {
    id: "a0ff5e9e078e",
    name: "Trailer Batch Pump BLP - W/25",
    slug: "trailer-batch-pump-blp-w-25",
    brand: "Batch pump",
    category: "batch-pump",
    className: "product-item-batch",
    imageUrl: "ProductData[22]",
    localImage: "trailer-batch-pump-blp-w-25-a4aa4880.png",
    details: {
      "Max. Theo Pumping Output": "40 m3/h",
      "System Pressure": "28 Mpa",
      "Delivery Cylinder x Stroke ": "Φ200X1000",
      "Distribute Valve": "S Valve",
      Generator: "100 kW",
      "Main Motor": "37 kW",
      "Main Pump": "Flutek Kawasaki K3V112",
      "Hopper Capacity": "1.8 m3",
    },
    url: null,
  },
  {
    id: "fc4cd5bb0431",
    name: "Batch Pump BLP - W/40",
    slug: "batch-pump-blp-w-40",
    brand: "Batch pump",
    category: "batch-pump",
    className: "product-item-batch",
    imageUrl: "ProductData[0]",
    localImage: "batch-pump-blp-w-25-327b6bd1.png",
    details: {
      "Max. Theo Pumping Output": "40 m3/h",
      "System Pressure": "28 Mpa",
      "Delivery Cylinder x Stroke ": "Φ200X1262",
      "Distribute Valve": "S Valve",
      Generator: "120 kW",
      "Main Motor": "37 kW",
      "Main Pump": "KAWASAKI 140",
      "Hopper Capacity": "1.8 m3",
    },
    url: null,
  },
  {
    id: "0a043ecf2c93",
    name: "Zoomlion QY 55",
    slug: "zoomlion-qy-55",
    brand: "Crane",
    category: "crane",
    className: "product-item-bland",
    imageUrl: "ProductData[26]",
    localImage: "zoomlion-qy-55-d27c5c87.png",
    details: {
      "Max. rated lifting capacity": "55t",
      "Max. load moment of basic boom": "1568kN.m",
      "Max. load moment of main boom (fully extended)": "940.8kN.m",
      "Max. lifting height of basic boom": "11.8m",
      "Max. lifting height of main boom": "44m",
      "Max. lifting height of jib": "60m",
    },
    url: null,
  },
  {
    id: "9330a4fa2ec7",
    name: "Zoomlion QY 25",
    slug: "zoomlion-qy-25",
    brand: "Crane",
    category: "crane",
    className: "product-item-bland",
    imageUrl: "ProductData[25]",
    localImage: "zoomlion-qy-25-a4f13453.png",
    details: {
      "Max. rated lifting capacity": "25t",
      "Max. load moment of basic boom": "1067kN.m",
      "Max. load moment of main boom (fully extended)": "700kN.m",
      "Max. lifting height of basic boom": "11.3m",
      "Max. lifting height of main boom": "42.1m",
      "Max. lifting height of jib": "50m",
    },
    url: null,
  },
];

export const productCategoryFilter = [
  {
    label: "All",
    value: "all",
  },
  ...Array.from(new Set(products.map((p) => p.category))).map((category) => ({
    label: category
      .split("-")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" "),
    value: category,
  })),
];

export const productServiceFooter = Array.from(
  new Set(products.map((p) => p.category))
).map((category, idx) => ({
  label: "View Products",
  url: "/products",
}));
